############################# Begin_Citation [1] ########################### 
geometry_msgs/Point[] waypoints
############################# End_Citation [1] #############################
---
float64 distance
